### ISSUE TITLE
SELinux blocking socket

### ISSUE THREAD

**Issue by runcom** [runcom/docker-novolume-plugin#2]
/cc @rhatdan 

just to track SELinux is blocking the connection back to the docker daemon

```
docker: Error response from daemon: Plugin Error: Cannot connect to the Docker daemon. Is the docker daemon running on this host?, AuthZPlugin.AuthZReq.
```

I'm still looking for the cause..disabling SELinux (deeply sorry Dan) will fix this though

**Comment by rhatdan** [comment]
This is a policy issue.  We are blocking init_t domains from talking to docker_t.

ps -eZ | grep docker

What is the docker volume plugin running with.

You can fix this by changing the label of the executable to docker_exec_t.

chcon -R -t docker_exec_t /var/lib/docker

Then restart your daemon.  We need to make this change if we decide this is the location for these plugins.  Or we could move the plugins to /usr/sbin and then change the label there in the docker-selinux package.

**Comment by runcom** [comment]
> What is the docker volume plugin running with.

you're right

```
system_u:system_r:init_t:s0       433 ?        00:00:00 docker-novolume
system_u:system_r:docker_t:s0     587 ?        00:00:00 docker
```

> You can fix this by changing the label of the executable to docker_exec_t.
> 
> chcon -R -t docker_exec_t /var/lib/docker
> 
> Then restart your daemon. We need to make this change if we decide this is the location for these plugins. Or we could move the plugins to /usr/sbin and then change the label there in the docker-selinux package.

how do we `chcon` on plugin installation? (I'm not understanding :/)
generally, how do we change selinux label upon installation?

**Comment by rhatdan** [comment]
We need to fix this in docker-selinux package, I am just giving you a work around to make sure it works for you.

We just need to decide on the path we want for docker-novolume, then I can setup the proper labeling.

**Comment by runcom** [comment]
awesome (I'll keep this open as a reminder though)

**Comment by runcom** [comment]
@rhatdan any hints on how I could fix this i docker-selinux? I have no idea right now, so we can move on with this

**Comment by rhatdan** [comment]
Just pushed some policy for this to the docker-selinux package.  I will send you something to test.

**Comment by runcom** [comment]
fixed in latest docker-selinux pkg shipped in rawhide
